steps:
  - name: ":rspec:"
    command: "scripts/ci/parallel_specs.sh"
    artifact_paths: "log/**/*"
    env:
      RAILS_ENV: test
    plugins:
      docker-compose#v2.5.0:
        run: app
    parallelism: 4
    agents:
      queue: $BUILDKITE_AGENT_META_DATA_QUEUE
